### ISSUE TITLE
fastQTL strand 

### ISSUE THREAD

**Issue by cindywen96** [francois-a/fastqtl#15]
Hi! I noticed in GTEx expression matrix preparation script, when converting from GTF to BED, for genes on +strand, the coordinates become (start-1, start), and for genes on -strand, coordinates become (end-1, end). I wonder how is FastQTL dealing with strand as the BED matrix does not have a strand column. Is this conversion specific to this extended version of FastQTL, or is it the correct way to prepare expression.bed matrix for general use of FastQTL? Thank you!!

**Comment by francois-a** [comment]
Hi, 

That's right -- the GTF is parsed this way to identify the TSS, since the cis-window is defined around the TSS (typically ±1Mb). Strand does not matter in QTL mapping. If the RNA-seq protocol was stranded, the strandedness would be taken account upstream, as part of quantifying read counts. Please also check out [tensorQTL](https://github.com/broadinstitute/tensorqtl) for QTL mapping.

**Comment by cindywen96** [comment]
Thank you for your reply! So when generating phenotype.bed file from gtf, genes on reverse/minus strand got TSS onto the forward strand, and since the genotype coordinates are forward-stransded, QTL results are all on forward direction?

**Comment by cindywen96** [comment]
Thank you for your reply!!
